Pythagorean triple
A Pythagorean triple is called primitive, if gcd(x,y,z)=1
Properties:
All primitive Pythagorean triples are given by:
x=2mn,y=x^2-y^2,z=x^2+y^2
where m and n are relatively-prime positive integers, and m>n.
Every non-primitive Pythagorean triple a positive integer multiple of a primitive triple. These may also be generated by including relatively-prime integers for m and n.
